controller_manager:
  ros__parameters:
    update_rate: 50

    diff_cont:
      type: diff_drive_controller/DiffDriveController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

diff_cont:
  ros__parameters:
    left_wheel_names: ["fl_wheel_joint", "bl_wheel_joint"]
    right_wheel_names: ["fr_wheel_joint", "br_wheel_joint"]
    wheel_separation: 0.3
    wheel_radius: 0.05
    base_frame_id: base_link
    cmd_vel_timeout: 0.5
    publish_rate: 50.0
    use_stamped_vel: false
